### ISSUE TITLE
<script> tag inside lazy <script> tag

### ISSUE THREAD

**Issue by baszero** [madgex/lazy-ads#14]
Hi,
some advertisers provide just a single line for inserting their ads from their adservers, e.g.

`<script language="javascript" type="text/javascript" src="..."></script>`

At a first try this did not work out, the error was "$ is not defined".
Do I have to replace the one-liner by something else like a function calling the script of the advertiser?

Thanks for any hints.

**Comment by kristian-b** [comment]
Hello,

on my page I have single line ads too and lazy-ads is working fine. I don't think there is any difference.

**Comment by baszero** [comment]
Ok thanks a lot!
